[[language]]
name = "tsx"
language-servers = [ "typescript-language-server","tailwindcss-ls"]
formatter = { command = "prettier" , args = ["--parser", "typescript"]}
file-types = ["tsx", "ts"]
auto-format = true

[[language]]
name = "html"
language-servers = [ "tailwindcss-ls", "vscode-html-language-server" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]



[[language]]
name = "python"
auto-format = true
language-servers = ["pylsp","pyright","ruff"]
formatter = {command = "black" , args = ["--line-length","88","--quiet","-"]}


[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python3"
args = ["-m",  "debugpy.adapter"]

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.pylint.enabled = true
plugins.pyflakes.enabled = true
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = true
plugins.rope_autoimport.enabled = true
plugins.ruff.enabled = true

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }
